<a href="https://colab.research.google.com/github/Marcjazz/py-playground/blob/master/learning_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(4)

In [ ]:
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2, 5, -4])
print(tensor_one_d)

tf.Tensor([ 2  5 -4], shape=(3,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [2, 4, 10],
    [-37, 3, 8],
    [0, 1, 6]
])
print(tensor_two_d)

tf.Tensor(
[[  2   4  10]
 [-37   3   8]
 [  0   1   6]], shape=(3, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [[2, 4, 10],
    [-37, 3, 8],
    [0, 1, 6]],
    [[1, 4, 10],
    [-7, 3, 9],
    [5, 1, 6]]
])
print(tensor_three_d)

tf.Tensor(
[[[  2   4  10]
  [-37   3   8]
  [  0   1   6]]

 [[  1   4  10]
  [ -7   3   9]
  [  5   1   6]]], shape=(2, 3, 3), dtype=int32)


In [ ]:
tensor_four_d = tf.constant([
    [
        [
            [  2,   4,  10],
            [-37,   3,   8],
            [  0,   1,   6]
        ],
        [
            [  1,   4,  10],
            [ -7,   3,   9],
            [  5,   1,   6]
        ]
    ],
    [
        [
            [  2,   4,  10],
            [-37,   3,   8],
            [  0,   1,   6]
        ],
        [
            [  1,   4,  10],
            [ -7,   3,   9],
            [  5,   1,   6]
        ]
    ]
])
print(tensor_four_d)

tf.Tensor(
[[[[  2   4  10]
   [-37   3   8]
   [  0   1   6]]

  [[  1   4  10]
   [ -7   3   9]
   [  5   1   6]]]


 [[[  2   4  10]
   [-37   3   8]
   [  0   1   6]]

  [[  1   4  10]
   [ -7   3   9]
   [  5   1   6]]]], shape=(2, 2, 3, 3), dtype=int32)


In [ ]:
print(tensor_four_d.ndim)

4


In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1,3,6])
print(np_array)

[1 3 6]


In [ ]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2, 5],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0.

In [ ]:
fill_tensor = tf.fill(
    [1, 3, 4], 5, name=None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


In [ ]:
zeros_tensor = tf.zeros([3,2], dtype=tf.dtypes.float32)
print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [ ]:
ones_tensor = tf.ones([3,2], dtype=tf.dtypes.float32)
print(ones_tensor)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [ ]:
random_tensor = tf.random.normal(
    [3, 2],
    mean=10,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 8.551605  9.766801]
 [10.377896  9.941081]
 [ 9.390472  9.697335]], shape=(3, 2), dtype=float32)
